name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # idk
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_MASKED_TIME: "False" # optional
          STOP_AT_OTHER: "TRUE" # optional
          IGNORED_LANGUAGES: "YAML TOML" # optional
          SHOW_DAYS_OF_WEEK: "False" # optional
          SHOW_EDITORS: "False" # optional
          SHOW_LANGUAGE: "False" # optional
          SHOW_OS: "False" # optional
          SHOW_LANGUAGE_PER_REPO: "False" # optional
          SHOW_SHORT_INFO: "False" # optional
          SHOW_TIMEZONE: "False" # optional
          SHOW_UPDATED_DATE: "False" # optional
          UPDATED_DATE_FORMAT: "%d/%m/%Y" # optional
          SHOW_PROJECTS: "False" # optional
          SHOW_LINES_OF_CODE: "False" # optional
          SHOW_LOC_CHART: "False" # optional
          LOCALE: "en" # optional
          SHOW_PROFILE_VIEWS: "False" # optional
